version: '3.7'
services:
  backend:
    build: ./backend
    command:
      sh -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/support
      - static_volume:/static
      - media_volume:/media
    expose:
      - 8000
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=*****
      - POSTGRES_PASSWORD=*****
      - POSTGRES_DB=*****
    ports:
      - '5432:5432'

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - static_volume:/usr/src/support/static
      - media_volume:/usr/src/support/media
    depends_on:
      - backend
    restart: always

  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'

  celery:
    build: ./backend
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/usr/src/support
    env_file:
      - .env
    depends_on:
      - redis
      - backend

volumes:
  postgres_data:
  media_volume:
  static_volume: